name: Weekly OSM

env:
  RENV_PATHS_ROOT: ~/.local/share/renv

on:
  schedule:
    - cron: '13 3 * * 1'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - name: Install libcurl
      run: |
        sudo apt-get update
        sudo apt-get install libcurl4-openssl-dev
    # clone ruevko/weekly-osm
    - name: Checkout repository
      uses: actions/checkout@v3
    # create/restore cache
    - name: Cache packages
      uses: actions/cache@v3
      with:
        path: ${{ env.RENV_PATHS_ROOT }}
        key: renv-${{ hashFiles('renv.lock') }}
        restore-keys: |
          renv-
    # install/restore packages
    - name: Restore packages
      run: Rscript -e 'renv::restore()'
    # source main script
    - name: Obtain weekly data
      run: Rscript R/main.R
    # commit and push
    - name: Commmit data
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add data readme.md
        git commit -m "${{ env.GH_MSG }}"
        git push
