name: Weekly OSM

env:
  RENV_PATHS_ROOT: ~/.local/share/renv

on: workflow_dispatch

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - name: Install libcurl
      run: sudo apt-get install libcurl4-openssl-dev
    # clone ruevko/weekly-osm
    - name: Checkout repository
      uses: actions/checkout@v2
    # create/restore cache
    - name: Cache packages
      uses: actions/cache@v2
      with:
        path: ${{ env.RENV_PATHS_ROOT }}
        key: renv-${{ hashFiles('renv.lock') }}
        restore-keys: |
          renv-
    # install/restore packages
    - name: Restore packages
      run: Rscript -e 'renv::restore()'
    # source main script
    - name: Obtain weekly data
      run: Rscript -e 'source("R/read_all_data.R");glimpse(weekly_osm_data)'
